# Generated by Django 3.0.5 on 2020-04-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_name', models.CharField(max_length=200)),
                ('team_name_abbr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_address', models.CharField(max_length=200)),
                ('team_city', models.CharField(max_length=200)),
            ],
        ),
    ]
