language: python
python:
  - "3.7"
services: mysql
# command to install dependencies
before_install:
  - pip install mysql
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - mysql -u root --password=""
script:
  - coverage run manage.py test -v 2
  - coveralls
